# Generated by Django 4.2.5 on 2023-11-22 15:58

import church.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=45)),
                ('postal_code', models.CharField(max_length=20)),
                ('address_line', models.CharField(max_length=25)),
                ('date_baptized', models.DateField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=church.models.image_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
